{% set name = "celery-redbeat" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 36b98c32ea4ca6f6f1ccddc3fdb9f5cd7a4bd273650cf931c6c46fb7fbc60a91

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - celery
    - pip
    - python
    - python-dateutil
    - redis-py
    - tenacity
  run:
    - celery
    - python
    - python-dateutil
    - redis-py
    - tenacity

test:
  imports:
    - redbeat

about:
  home: https://github.com/sibson/redbeat
  license: Apache Software
  license_family: APACHE
  license_file: LICENSE
  summary: A Celery Beat Scheduler using Redis for persistent storage
  doc_url: https://redbeat.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - soapy1
