{% set name = "celery-redbeat" %}
{% set version = "2.3.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz"
  sha256: f52664b490b2923a787d9f348f291243601430bf8ec383b6e79870a1731ee92a

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - celery
    - pip
    - python {{ python_min }}
    - python-dateutil
    - redis-py
    - tenacity
  run:
    - celery
    - python >={{ python_min }}
    - python-dateutil
    - redis-py
    - tenacity

test:
  requires:
    - python {{ python_min }}
  imports:
    - redbeat

about:
  home: "https://github.com/sibson/redbeat"
  license: Apache Software
  license_family: APACHE
  license_file: LICENSE
  summary: "A Celery Beat Scheduler using Redis for persistent storage"
  doc_url: "https://redbeat.readthedocs.io/en/latest/"

extra:
  recipe-maintainers:
    - soapy1
