{% set name = "celery-redbeat" %}
{% set version = "2.4.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/celery_redbeat-{{ version }}.tar.gz"
  sha256: c429ae50de25475e07c31e06261da6f6b7b8179f7e35f13060bafe6f7d3bf3ec

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - celery >=5.0
    - python >={{ python_min }}
    - python-dateutil
    - redis-py >=3.2
    - tenacity

test:
  requires:
    - python {{ python_min }}
  imports:
    - redbeat

about:
  home: "https://github.com/sibson/redbeat"
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: "A Celery Beat Scheduler using Redis for persistent storage"
  doc_url: "https://redbeat.readthedocs.io/en/latest/"

extra:
  recipe-maintainers:
    - soapy1
