travis:
  secure:
    BINSTAR_TOKEN: VqgnA1Bz24N42p0znG/N/9z91v6wvAyYiftp2rc/sDRKnfVjMEuUTIqVGou9YJvMs0PUzl9VGdM42mhTcU6QYgvZguNixPTxq23ZvcsJv1djNd9fPrYu1VfxibSUNUN+m70/y/R2vY/DBn/nKjkn/ltwrkutir7P93ReLFO8JwcDgPzcFxqzt/0Dlvh4AKkmsLfjd9e2MJoEBH4zQhjI88Wk6uP321spR2iCuRX3C1lmMijFkRV0OJjkcoosYxEZvRvHFJilu4JcZBqc/6l8AvPZOoQIVozR/t/85JeD8IofNCrdC6KUmpudQm33+W3/cjiXL25/XYy6fJTlTBm8IwEuoAaa3IXYnxxbDl0Cv2zo0xYz97tDlyMUWfAWbJug/cw52dMw2KU3XB9m+41Krll5pAknQGI0TF1HiLSCquL4Xc2oncGs7g9SYoAPow5FD1OSjDB3cy2J336FVMhQGdtJGQNZ57fyZuMhrnQMoaCjTZBFMxWAGgoMSfsNJF0z8WJkIa0A/gPOt4iiNJbSNM9GfHG0Njn+dhyPq95T0KHfATYEcULtWgR44HXEgcqrit2EkHoqOVf7pI8wjVAzL51tsji2Ba9baDGZDQdU+DFwMuwHuXY50c/2uldODjcGh0gKmIHxmtm5o+Ype4qM+ucJtDREfzyeAzgR/ePrOvQ=
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
